development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: euvendomicrosol_development
  pool: 5
  username: root
  password:
  host: localhost
  socket: /Applications/XAMPP/xamppfiles/var/mysql/mysql.sock
